#
# Common Configuration for all the environments
#
spring: 
 application: 
  name: we-shopify-platform
 thymeleaf: 
  cache: false
 jpa:    hibernate:      ddl-auto: update
    show-sql: true
 profiles: 
   active: ${APP_PROFILE:dev}     
   
server: 
 port: 5001
 
weshopify: 
 app: 
  search: 
   keys: ByEmail,ByMobile,ByUserName

---
#
# Dev Environment Configurations
#
spring: 
 profiles: dev
 datasource: 
  driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:weshopify-app}
  username: ${DB_USER_NAME:root} 
  password: ${DB_USER_PWD:root}
---
#
# QA Environment Configurations
#
spring: 
 profiles: qa
 h2:    console:      enabled: true
      path: /h2Console
 datasource: 
  driver-class-name: ${DB_DRIVER:org.h2.Driver}
  url: jdbc:${DB_TYPE:h2}:mem:${DB_SCHEMA:weshopify-app}
  username: ${DB_USER_NAME:sa}
  password: ${DB_USER_NAME:sa}
  